name: Generate Presentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-pptx

    - name: Run script
      run: |
        python create_presentation.py

    - name: Upload presentation
      uses: actions/upload-artifact@v2
      with:
        name: presentation
        path: |
          Understanding_and_Addressing_Mental_Health_Issues_in_Young_People.pptx
